#! /bin/sh

# Path to GDB macros file.  Customize for your site.
# Try multiple locations for flexibility
if test -f "$HOME/.bin/gdb-macros"; then
	GDBMACROS="$HOME/.bin/gdb-macros"
elif test -f "/home/vagrant/.bin/gdb-macros"; then
	GDBMACROS="/home/vagrant/.bin/gdb-macros"
elif test -f "$(dirname "$0")/../misc/gdb-macros"; then
	GDBMACROS="$(dirname "$0")/../misc/gdb-macros"
else
	GDBMACROS=""
fi

# Choose correct GDB.
if command -v i386-elf-gdb >/dev/null 2>&1; then
	GDB=i386-elf-gdb
else
	GDB=cgdb
fi

# Run GDB.
if test -n "$GDBMACROS" && test -f "$GDBMACROS"; then
	exec $GDB -x "$GDBMACROS" "$@"
else
	if test -n "$GDBMACROS"; then
		echo "*** $GDBMACROS does not exist ***"
	fi
	echo "*** Pintos GDB macros will not be available ***"
	exec $GDB "$@"
fi
